#
# start
#
spring:
  main:
    banner-mode: "off"
    
chutes-ladders:
  board-size: 100
  spinner-size: 6
  players:
    - name: John
    - name: Mary
    - name : Bharath
    - name : Erica
  ladders:
    1 : 38
    4 : 14
    9 : 31
    21: 42
    28: 84
    36 : 44
    51 : 67
    80: 100
  chutes:
    16 : 6
    47 : 26
    49 : 11
    56 : 53
    62 : 19
    64 : 60
    87 : 24
    93 : 73
    95 : 75
    98 : 78
#
# End
#